# Generated by Django 5.1 on 2024-08-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('fecha_nac', models.DateField()),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('nombre_apellido_paterno', models.CharField(max_length=100)),
                ('nombre_apellido_materno', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('domicilio_actual', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('ministerio', models.CharField(max_length=100)),
                ('registro', models.CharField(max_length=100)),
                ('tipo_pabellon', models.CharField(max_length=100)),
                ('numero_pabellon', models.CharField(max_length=100)),
                ('seccion_pabellon', models.CharField(max_length=100)),
                ('otros_pabellon', models.CharField(blank=True, max_length=255, null=True)),
                ('autorizacion_iglesia', models.FileField(upload_to='autorizaciones/')),
            ],
        ),
    ]
