# Generated by Django 5.1 on 2024-09-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_registro_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
