# Generated by Django 5.1 on 2024-10-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_registro_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='unidad_carcelaria',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
